### ISSUE TITLE
Other projects coming to mind

### ISSUE THREAD

**Issue by JayPanoz** [caraya/reading-experience#1]
Hey, thanks for letting me know this repo exists. This text is pretty dense and I'll have to take the time to explore it further. Anyways, at first reading, a few links come to mind: 
1. [Pelican Books](https://www.pelicanbooks.com) → read online. What's interesting here is probably the design articles in which you can grasp the designers’ insights, for instance [“How Pelican Books is reimagining the cover in the digital age of eBooks”](http://www.fastcodesign.com/3038698/how-pelican-books-is-reimagining-the-cover-in-the-age-of-e-books) or [“Pelican Books: an unrivalled online reading experience”](https://www.creativereview.co.uk/cr-blog/2014/november/pelican-books-an-unrivalled-online-reading-experience/) ;
2. [The Shape of Design](http://shapeofdesignbook.com) by Frank Chimero and the approach behind it: [“Designing in the borderlands”](http://www.frankchimero.com/writing/designing-in-the-borderlands/), in which you can see eBook tech has constrained the whole project;
3. [Butterick’s Practical Typography](http://practicaltypography.com) and the publishing system powering it, [Pollen](http://docs.racket-lang.org/pollen/).

Sure, everything may not necessarily fit in, especially as we're taking PWA, but at least I guess there’s a lot of interesting insights which could somehow extend this reflection.

Truth is more and more books are published online but it’s quite difficult to pay attention and keep track. For instance, right now I can’t retrieve the link about online catalogues published by a museum some weeks ago in #eprdctn.

That being said, once you start researching all those projects a little bit, it turns out to be a gold mine of information. So yeah, it would probably be a good idea to list all those online books someday.

**Comment by caraya** [comment]
What drove me into the fray was Craig Mod's [Subcompact Publishing](http://craigmod.com/journal/subcompact_publishing/)  particularly the speed of publishing and thus closing the loop between author/publisher and reader

The other issue is that pretty much everyone trying new approaches to publishing creates a new framework or uses a new language in the implementation. I may be dating myself but want to go back to the old HTML, CSS and Javascript approach... no framework, no new language, no new library

**Comment by caraya** [comment]
Breaking them out into a separate document.
